[package]
name = "dionysus"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["console"] }
console_error_panic_hook = "0.1.7"
wee_alloc = "0.4.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
